name: publish

on:
  pull_request:
    branches: [main]
#on:
#  release:
#    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/certainly-not-python-client
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: make bootstrap
      - name: Build package
        run: make build-wheel
      - name: Publish to PyPI
        env:
          PYPI_USERNAME: __token__
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: make publish-to-pypi
