name: Tests fonctionels

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-tests:
    name: Tests fonctionnels
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.9

      - name: Install dependencies in venv
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install .
          pip install -r requirements_for_test.txt

      - name: Run function tests (mocked)
        run: |
          source venv/bin/activate
          pytest integration_test/integration_tests_mocked.py

      - name: Run unit tests
        run: |
          source venv/bin/activate
          pytest tests/
