name: Trivy Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  docker-scan:
    name: Scan de securite Trivy (Docker image)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t notifications-python-client .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: notifications-python-client
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

   filesystem-scan:
    name: Scan de securite Trivy (filesystem via SBOM)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies in venv
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install .    # installe ta lib
          pip install -r requirements_for_test.txt

      - name: Install CycloneDX generator
        run: |
          source venv/bin/activate
          pip install cyclonedx-bom

      - name: Generate SBOM (CycloneDX)
        run: |
          source venv/bin/activate
          cyclonedx-py -o sbom.json

      - name: Scan SBOM with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: sbom
          scan-ref: sbom.json
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH
